# Generated by Django 3.2.12 on 2022-04-04 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_app', '0033_binningprogress'),
        ('rnames_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyTimeSlice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_on', models.DateTimeField(auto_now=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnames_api.userapikey')),
                ('time_slice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnames_app.timeslice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
