# Generated by Django 3.2.13 on 2022-06-05 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_api', '0002_keytimeslice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyTimeSlice',
        ),
    ]
