# Generated by Django 3.2.13 on 2022-06-07 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_app', '0045_absoluteagevalue_historicalabsoluteagevalue'),
        ('rnames_api', '0003_delete_keytimeslice'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyAbsoluteAgeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_on', models.DateTimeField(auto_now=True)),
                ('absolute_age_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnames_app.absoluteagevalue')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnames_api.userapikey')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
