# Generated by Django 4.1.3 on 2022-12-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_api', '0005_alter_userapikey_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keylocation',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='keylocation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='keyname',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='keyname',
            name='name',
        ),
        migrations.RemoveField(
            model_name='keyqualifier',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='keyqualifier',
            name='qualifier',
        ),
        migrations.RemoveField(
            model_name='keyqualifiername',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='keyqualifiername',
            name='qualifier_name',
        ),
        migrations.RemoveField(
            model_name='keyreference',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='keyreference',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='keyrelation',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='keyrelation',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='keystratigraphicqualifier',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='keystratigraphicqualifier',
            name='stratigraphic_qualifier',
        ),
        migrations.RemoveField(
            model_name='keystructuredname',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='keystructuredname',
            name='structured_name',
        ),
        migrations.DeleteModel(
            name='KeyAbsoluteAgeValue',
        ),
        migrations.DeleteModel(
            name='KeyLocation',
        ),
        migrations.DeleteModel(
            name='KeyName',
        ),
        migrations.DeleteModel(
            name='KeyQualifier',
        ),
        migrations.DeleteModel(
            name='KeyQualifierName',
        ),
        migrations.DeleteModel(
            name='KeyReference',
        ),
        migrations.DeleteModel(
            name='KeyRelation',
        ),
        migrations.DeleteModel(
            name='KeyStratigraphicQualifier',
        ),
        migrations.DeleteModel(
            name='KeyStructuredName',
        ),
    ]
