# Generated by Django 3.2.13 on 2022-05-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_app', '0034_binningscheme_binningschemename_historicalbinningscheme_historicalbinningschemename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binningschemename',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='binningschemename',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='binningschemename',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='binningschemename',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='binningschemename',
            name='modified_on',
        ),
        migrations.DeleteModel(
            name='HistoricalBinningSchemeName',
        ),
    ]
