# Generated by Django 3.2.13 on 2022-06-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_app', '0035_auto_20220508_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binning',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='binningscheme',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='historicalbinning',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='historicalbinningscheme',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='historicallocation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='historicalname',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='historicalqualifier',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='historicalqualifiername',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='historicalreference',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='historicalrelation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='historicalstratigraphicqualifier',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='historicalstructuredname',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='historicaltimeslice',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='location',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='name',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='qualifier',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='qualifiername',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='stratigraphicqualifier',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='structuredname',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='timeslice',
            name='is_active',
        ),
    ]
