# Generated by Django 3.2.13 on 2022-06-05 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_app', '0036_auto_20220603_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binning',
            name='binning_scheme',
            field=models.ForeignKey(help_text='The Binning Scheme', on_delete=django.db.models.deletion.CASCADE, to='rnames_app.binningscheme'),
        ),
        migrations.AlterField(
            model_name='historicalbinning',
            name='binning_scheme',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The Binning Scheme', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rnames_app.binningscheme'),
        ),
    ]
