# Generated by Django 3.2.13 on 2022-06-05 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_api', '0003_delete_keytimeslice'),
        ('rnames_app', '0037_auto_20220605_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='timeslice',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='HistoricalTimeSlice',
        ),
        migrations.DeleteModel(
            name='TimeSlice',
        ),
    ]
