# Generated by Django 3.2.13 on 2022-06-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_app', '0038_auto_20220605_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='binningscheme',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Are the scheme and its results public'),
        ),
        migrations.AddField(
            model_name='historicalbinningscheme',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Are the scheme and its results public'),
        ),
    ]
