# Generated by Django 3.2.13 on 2022-06-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_app', '0038_auto_20220606_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='timeslice',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='binningscheme',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Are the scheme and its results public'),
        ),
        migrations.AddField(
            model_name='historicalbinningscheme',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Are the scheme and its results public'),
        ),
        migrations.DeleteModel(
            name='HistoricalTimeSlice',
        ),
        migrations.DeleteModel(
            name='TimeSlice',
        ),
    ]
