# Generated by Django 3.2.13 on 2022-06-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_app', '0039_auto_20220606_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso3166_1_alpha_2', models.CharField(help_text='ISO 3166-1 alpha-2 country code', max_length=2, unique=True)),
                ('official_name_en', models.CharField(help_text='Official English name', max_length=255)),
                ('region_name', models.CharField(help_text='Region Name', max_length=255)),
            ],
        ),
    ]
