# Generated by Django 3.2.13 on 2022-06-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_app', '0042_auto_20220607_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binningschemename',
            old_name='order',
            new_name='sequence',
        ),
        migrations.RenameField(
            model_name='binningschemename',
            old_name='scheme',
            new_name='ts_name',
        ),
        migrations.AlterUniqueTogether(
            name='binningschemename',
            unique_together={('ts_name', 'structured_name'), ('ts_name', 'sequence')},
        ),
    ]
