# Generated by Django 3.2.13 on 2022-06-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_app', '0043_auto_20220607_1643'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountryCodes',
            new_name='CountryCode',
        ),
    ]
