# Generated by Django 3.2.13 on 2022-06-07 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rnames_app', '0044_rename_countrycodes_countrycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAbsoluteAgeValue',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('modified_on', models.DateTimeField(blank=True, editable=False)),
                ('history_change_reason', models.TextField(null=True)),
                ('age', models.FloatField(help_text='Absolute Age in millions of years')),
                ('age_upper_confidence', models.FloatField(default=0, help_text='Upper Confidence Value in millions of years')),
                ('age_lower_confidence', models.FloatField(default=0, help_text='Lower Confidence Value in millions of years')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('reference', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rnames_app.reference')),
                ('structured_name', models.ForeignKey(blank=True, db_constraint=False, help_text='Absolute Age Structured Name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rnames_app.structuredname')),
            ],
            options={
                'verbose_name': 'historical absolute age value',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AbsoluteAgeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('age', models.FloatField(help_text='Absolute Age in millions of years')),
                ('age_upper_confidence', models.FloatField(default=0, help_text='Upper Confidence Value in millions of years')),
                ('age_lower_confidence', models.FloatField(default=0, help_text='Lower Confidence Value in millions of years')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_absoluteagevalue', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_absoluteagevalue', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnames_app.reference')),
                ('structured_name', models.ForeignKey(help_text='Absolute Age Structured Name', on_delete=django.db.models.deletion.CASCADE, to='rnames_app.structuredname')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
