# Generated by Django 3.2.15 on 2022-09-16 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_app', '0046_auto_20220619_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binning',
            name='name',
        ),
        migrations.RemoveField(
            model_name='binning',
            name='oldest_name',
        ),
        migrations.RemoveField(
            model_name='binning',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='binning',
            name='ts_count',
        ),
        migrations.RemoveField(
            model_name='binning',
            name='youngest_name',
        ),
        migrations.RemoveField(
            model_name='historicalbinning',
            name='name',
        ),
        migrations.RemoveField(
            model_name='historicalbinning',
            name='oldest_name',
        ),
        migrations.RemoveField(
            model_name='historicalbinning',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='historicalbinning',
            name='ts_count',
        ),
        migrations.RemoveField(
            model_name='historicalbinning',
            name='youngest_name',
        ),
    ]
