# Generated by Django 3.2.15 on 2022-09-16 17:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_app', '0049_auto_20220916_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinningAbsoluteAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refs', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('oldest_age', models.FloatField(default=0, help_text='Lower Confidence Value in millions of years')),
                ('youngest_age', models.FloatField(default=0, help_text='Upper Confidence Value in millions of years')),
                ('reference_age', models.FloatField(default=0, help_text='Age in millions of years')),
                ('age_constraints', models.CharField(max_length=255)),
                ('binning_scheme', models.ForeignKey(blank=True, help_text='The Binning Scheme', null=True, on_delete=django.db.models.deletion.CASCADE, to='rnames_app.timescale')),
                ('oldest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rnames_app.structuredname')),
                ('structured_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rnames_app.structuredname')),
                ('youngest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rnames_app.structuredname')),
            ],
        ),
    ]
