# Generated by Django 4.1.3 on 2022-12-12 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_api', '0006_remove_keylocation_api_key_and_more'),
        ('rnames_app', '0054_remove_binning_created_by_remove_binning_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalabsoluteagevalue',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rnames_api.userapikey'),
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rnames_api.userapikey'),
        ),
        migrations.AddField(
            model_name='historicalname',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rnames_api.userapikey'),
        ),
        migrations.AddField(
            model_name='historicalqualifier',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rnames_api.userapikey'),
        ),
        migrations.AddField(
            model_name='historicalqualifiername',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rnames_api.userapikey'),
        ),
        migrations.AddField(
            model_name='historicalreference',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rnames_api.userapikey'),
        ),
        migrations.AddField(
            model_name='historicalrelation',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rnames_api.userapikey'),
        ),
        migrations.AddField(
            model_name='historicalstratigraphicqualifier',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rnames_api.userapikey'),
        ),
        migrations.AddField(
            model_name='historicalstructuredname',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rnames_api.userapikey'),
        ),
        migrations.AddField(
            model_name='historicaltimescale',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rnames_api.userapikey'),
        ),
    ]
