version: '3.8'

services:

  web:
    image: palaeontologyhelsinki/rnames_staging
    restart: unless-stopped
    ports:
      - 8000:8000
    command: sh -c ./scripts/entrypoint.prod.sh
    volumes:
      - static:/vol/web
    env_file: 
      - ./.env
    depends_on:
      - redis
    container_name: rnames_web_staging

  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - static:/vol/web
      - ./nginx/certbot/www:/var/www/certbot/:ro
      - ./nginx/certbot/conf:/etc/nginx/ssl/:ro
    environment:
      - RNAMES_DOMAIN=${RNAMES_DOMAIN}
      - PMA_DOMAIN=${PMA_DOMAIN}
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    depends_on:
      - web
    container_name: rnames_nginx_staging

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./nginx/certbot/www:/var/www/certbot/:rw
      - ./nginx/certbot/conf:/etc/letsencrypt/:rw
      - ./nginx/certbot/log:/var/log/:rw

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports: 
      - 8001:80
    environment:
      - PMA_HOST=${DB_HOST}
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    container_name: rnames_phpmyadmin_staging

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    container_name: rnames_watchtower

  redis:
    image: redis
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    container_name: rnames_redis_staging

volumes:
  static:
