#!/usr/bin/env python
# coding: utf-8

import pandas as pd
import time

###################
# many PBDB structured names refer to absolute ages 
# these ages are coherent with in PBDB but not with other ages from e.g. younger publications
# to use PBDB age grouping a special binning algorithm is needed
# bin_fun_PBDB is doing this.
#

def bin_fun_PBDB (c_rels, c_strat, binning_scheme, ts_names, t_scales, imp_id):
    
    
    t_scheme = binning_scheme
    x_names = ts_names[ts_names['ts_name']==t_scheme]
    used_ts = t_scales[t_scales['ts_name_id']==x_names['id'].values[0]]
    # rename columns in order to make compatible with following code
    used_ts = used_ts[['structured_name_id', 'sequence']]
    used_ts.rename(columns={'structured_name_id':'ts', 'sequence': 'ts_index'},inplace = True)
    print(used_ts['ts'])
    
    # this object give the PDBD upload id(s)
    PBDB_id = imp_id
    if PBDB_id.shape[0]>0:
        PBDB_id = PBDB_id.drop_duplicates()

    # makes c_rels two-sided
    c_rels = c_rels[['id', 'name_one_id', 'name_two_id','name_one_qualifier_qualifier_name_name', 
                              'name_two_qualifier_qualifier_name_name', 
                              'name_one_remarks','name_two_remarks','reference_id', 'reference_year']]
    c_rels.rename(columns={'name_one_id': 'name_1', 'name_two_id':'name_2', 
                         'name_one_qualifier_qualifier_name_name': 'strat_qualifier_1',
                         'name_two_qualifier_qualifier_name_name': 'strat_qualifier_2'},inplace = True) # rename to fit following code
    # make c_rels two-sided
    c_relsx = c_rels[['id', 'name_2','strat_qualifier_2','name_1', 'strat_qualifier_1', 
                      'name_one_remarks','name_two_remarks','reference_id', 'reference_year']]
    c_relsx.columns = ['id', 'name_1','strat_qualifier_1','name_2', 'strat_qualifier_2',
                       'name_one_remarks','name_two_remarks','reference_id', 'reference_year']
    c_rels = pd.concat([c_rels.reset_index(drop=False), c_relsx.reset_index(drop=False)], axis=0)
    c_rels = c_rels.reset_index(drop=True)  
    
    # some PBDB downloaded structured names have only relations to Absolute time
    # these are ignored by binning-fun_id.binning_fun()
    # here we bin them according to their PBDB absolute age
    # xxxx
    # xxxx
    # xxxx
    
    # get PBDB based absolute ages of ts   
    ## here is the mistake ...
    # alle direkten relations von ts nach absolut age
    c_rels_abs = c_rels[c_rels['strat_qualifier_2'] =='mya'] # all absolute ages of ts
    print(c_rels_abs)
    c_rels_abs = c_rels_abs[(c_rels_abs['name_two_remarks']=='Autogenerated by PBDB importer.')] # all absolute ages of ts
    print(c_rels_abs)
    abs_ts = c_rels_abs[c_rels_abs['name_1'].isin(used_ts['ts'])]
    print(abs_ts)
    #abs_ages = c_strat[(c_strat['qualifier_qualifier_name_name']=='mya') &
    #                     (c_strat['remarks']=='Autogenerated by PBDB importer.')]
    #abs_ages = abs_ages[['id','name_name']]   
    #abs_ts = pd.merge(c_rels_abs_ts, abs_ages, how= 'inner', left_on="name_2", right_on="id")
    #abs_ts['name_name'] = pd.to_numeric(abs_ages['name_name'])
    
    # if ts with PBDB based ages exist:
    if abs_ts.shape[0]==0:     
        PBDB_names_binned = pd.DataFrame([] * 6, columns=['name', 'oldest','youngest', 'ts_count', 'refs', 'rule'])
        print('No PBDB based ages in binning scheme. Empty data frame returned.')

    if abs_ts.shape[0]>0:
        start = time.time()
    
        PBDB_ts_binned = pd.DataFrame([] * 6, columns=['name', 'oldest','youngest', 'ts_count', 'refs', 'rule'])
        PBDB_ts_binned_abs = pd.DataFrame([] * 6, columns=['name', 'oldest','youngest', 'ts_count', 'refs', 'rule'])
        for i in range(0,len(used_ts)):
            x_abs_ts = abs_ts[abs_ts['name_1'] == used_ts['ts'].iloc[i]];
            if x_abs_ts.shape[0] > 0:
                oldest = max(pd.to_numeric(x_abs_ts['name_2']))
                youngest = min(pd.to_numeric(x_abs_ts['name_2']))
                x_youngest = x_abs_ts[x_abs_ts['name_2'] == youngest]
                x_oldest = x_abs_ts[x_abs_ts['name_2'] == oldest]
                combi = pd.DataFrame([{'name': used_ts['ts'].iloc[i],
                                   'oldest': x_oldest['name_1'].iloc[0], 'youngest': x_youngest['name_1'].iloc[0],
                                   'ts_count': 0,'refs':PBDB_id['reference_id'].iloc[0], 'rule': 7.0}])
                combi_abs = pd.DataFrame([{'name': used_ts['ts'].iloc[i],
                                   'oldest': oldest, 'youngest': youngest,
                                   'ts_count': 0,'refs':PBDB_id['reference_id'].iloc[0], 'rule': 7.0}])
                PBDB_ts_binned = pd.concat([PBDB_ts_binned, combi], axis=0)
                PBDB_ts_binned_abs = pd.concat([PBDB_ts_binned_abs, combi_abs], axis=0)
            
        # get all other PBDB based absolute ages
        #c_rels_abs = pd.merge(c_rels_abs, abs_ages, how= 'inner', left_on="name_2", right_on="id")
        # df[~df["column"].isin(["value"])]
        #c_rels_abs = c_rels_abs[c_rels_abs['reference_id'] == PBDB_id['reference_id'].iloc[0]]
        c_rels_abs = c_rels_abs[~c_rels_abs['name_1'].isin(used_ts['ts'])]
    
        names_with_PBDB_age = c_rels_abs['name_1'].drop_duplicates()
        names_with_PBDB_age = names_with_PBDB_age.to_frame()
    
        PBDB_names_binned = pd.DataFrame([] * 6, columns=['name', 'oldest','youngest', 'ts_count', 'refs', 'rule'])
        for i in range(0,len(names_with_PBDB_age)):
            x_c_rels_abs = c_rels_abs[c_rels_abs['name_1'] == names_with_PBDB_age['name_1'].iloc[i]]
            if x_c_rels_abs.shape[0]>0:
                oldest = max(pd.to_numeric(x_c_rels_abs['name_2']))   
                youngest = min(pd.to_numeric(x_c_rels_abs['name_2']))
                x_strat_oldest = PBDB_ts_binned_abs[(PBDB_ts_binned_abs['youngest']<=oldest) & (PBDB_ts_binned_abs['oldest']>=oldest)]
                x_strat_youngest = PBDB_ts_binned_abs[(PBDB_ts_binned_abs['youngest']<=youngest) & (PBDB_ts_binned_abs['oldest']>=youngest)]
                if (x_strat_oldest.shape[0]>0) & (x_strat_youngest.shape[0]>0):
                    yts = used_ts[used_ts['ts']==x_strat_youngest['name'].iloc[0]]
                    ots = used_ts[used_ts['ts']==x_strat_oldest['name'].iloc[0]]
                    combi = pd.DataFrame([{'name': names_with_PBDB_age['name_1'].iloc[i],
                                       'oldest': x_strat_oldest['name'].iloc[0], 'youngest': x_strat_youngest['name'].iloc[0],
                                       'ts_count': yts['ts_index'].iloc[0]-ots['ts_index'].iloc[0],
                                       'refs':PBDB_id['reference_id'].iloc[0], 'rule': 7.1}])
                    PBDB_names_binned = pd.concat([PBDB_names_binned, combi], axis=0)
        end = time.time()
        dura = (end - start)/60
    
        print("############################################")
        print("The binning took", round(dura, 2), "minutes")
        print("############################################")
     
    return PBDB_names_binned  
