# https://nginx.org/en/docs/http/ngx_http_limit_req_module.html
# https://blog.nginx.org/blog/rate-limiting-nginx

# Rate limiting for signup and password reset.
limit_req_zone $binary_remote_addr zone=accounts_limit:10m rate=5r/m;

# Rate limiting for logins (more generous)
limit_req_zone $binary_remote_addr zone=login_limit:10m rate=15r/m;
